Fbb 33 user validation
PavelBoPavel/register pull request #12
Opened 2021-08-31 19:40 UTC by VasiliZas

2021-09-01 11:46 UTC, KaydunovDenis requested changes

2021-09-01 11:46 UTC, KaydunovDenis commented on src/main/java/com/tutrit/java/quickstart/validation/CheckUserName.java
> +        if (user.getName() == null || user.getSurname() == null) {
I think what need check minimum and maximum lenght word.
name > 3 and name < 20
Иначе можно создать юзеров с большими именами и положить сервер.

2021-09-01 11:46 UTC, KaydunovDenis commented on src/main/java/com/tutrit/java/quickstart/validation/Checkable.java
> +public interface Checkable  {
-> UserChecable
We will have SlotChecable
оr change name of trow exception, then Checable and ValidationException  will be common for User and Slot, etc..

2021-09-01 11:46 UTC, KaydunovDenis commented on src/main/java/com/tutrit/java/quickstart/validation/UserValidator.java
> +}
add empty line

2021-09-01 11:46 UTC, KaydunovDenis commented on src/test/java/com/tutrit/java/quickstart/validation/UserValidatorTest.java
> +}
add empty line

2021-09-01 11:46 UTC, KaydunovDenis commented on src/test/java/com/tutrit/java/quickstart/validation/UserValidatorTest.java
> +    }
add validation min and max lenght word

2021-09-01 11:46 UTC, KaydunovDenis commented on src/main/java/com/tutrit/java/quickstart/validation/UserValidator.java
> +            new CheckUserName(),
What about is Surname?
May be rename method or separete his

2021-09-01 11:46 UTC, KaydunovDenis commented on src/main/java/com/tutrit/java/quickstart/validation/Checkable.java
> +}
add empty line

2021-09-01 11:46 UTC, KaydunovDenis commented on src/main/java/com/tutrit/java/quickstart/validation/CheckUserSlot.java
> +}
add empty line

2021-09-01 11:46 UTC, KaydunovDenis commented on src/main/java/com/tutrit/java/quickstart/validation/CheckUserNotNull.java
> +}
add empty line

2021-09-01 11:46 UTC, KaydunovDenis commented on src/main/java/com/tutrit/java/quickstart/validation/CheckUserNotNull.java
> +public class CheckUserNotNull implements Checkable  {
May be need create common class for check on Null

2021-09-01 13:36 UTC, PavelBoPavel approved these changes

2021-09-01 17:24 UTC, VasiliZas commented on src/main/java/com/tutrit/java/quickstart/validation/CheckUserName.java
> +        if (user.getName() == null || user.getSurname() == null) {
Тогда нужно было это указать. я делал под то что было.

2021-09-01 17:25 UTC, VasiliZas commented on src/main/java/com/tutrit/java/quickstart/validation/Checkable.java
> +public interface Checkable  {
-> UserChecable

2021-09-01 17:27 UTC, VasiliZas commented on src/main/java/com/tutrit/java/quickstart/validation/Checkable.java
> +}
Везде где ты написал добавить, она по факту есть. С чего ты взял?

2021-09-01 17:30 UTC, VasiliZas commented on src/main/java/com/tutrit/java/quickstart/validation/CheckUserNotNull.java
> +public class CheckUserNotNull implements Checkable  {
Зачем?

2021-09-02 13:39 UTC, KaydunovDenis approved these changes
Это выглядит не совсем так, как я это представлял, но это будет работать. Возможно после экспертизы Макса, будет смысл что-то менять.

2021-09-02 18:58 UTC, trump-ny approved these changes

2021-09-02 18:59 UTC, merged